print("Content-Type: text/html\n\n")
print("<html lang='en'>")
print("<head>")
print("<meta charset='UTF-8'>")
print("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
print("<title>Home | Bean Boutique Coffee</title>")
print("<link rel='stylesheet' href='style.css'>")
print("</head>")
print("<body>")
-- Body content here
print("</body>")
print("</html>")
